// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.3
// source: error.proto

package merr

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientError int32

const (
	ClientError_PARAMS            ClientError = 0
	ClientError_INTERNAL          ClientError = 1
	ClientError_NOT_FOUND         ClientError = 2
	ClientError_UNAUTHORIZED      ClientError = 3
	ClientError_FORBIDDEN         ClientError = 4
	ClientError_TOO_MANY_REQUESTS ClientError = 5
)

// Enum value maps for ClientError.
var (
	ClientError_name = map[int32]string{
		0: "PARAMS",
		1: "INTERNAL",
		2: "NOT_FOUND",
		3: "UNAUTHORIZED",
		4: "FORBIDDEN",
		5: "TOO_MANY_REQUESTS",
	}
	ClientError_value = map[string]int32{
		"PARAMS":            0,
		"INTERNAL":          1,
		"NOT_FOUND":         2,
		"UNAUTHORIZED":      3,
		"FORBIDDEN":         4,
		"TOO_MANY_REQUESTS": 5,
	}
)

func (x ClientError) Enum() *ClientError {
	p := new(ClientError)
	*p = x
	return p
}

func (x ClientError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientError) Descriptor() protoreflect.EnumDescriptor {
	return file_error_proto_enumTypes[0].Descriptor()
}

func (ClientError) Type() protoreflect.EnumType {
	return &file_error_proto_enumTypes[0]
}

func (x ClientError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientError.Descriptor instead.
func (ClientError) EnumDescriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{0}
}

type ServerError int32

const (
	ServerError_INTERNAL_SERVER  ServerError = 0
	ServerError_INVALID_ARGUMENT ServerError = 1
)

// Enum value maps for ServerError.
var (
	ServerError_name = map[int32]string{
		0: "INTERNAL_SERVER",
		1: "INVALID_ARGUMENT",
	}
	ServerError_value = map[string]int32{
		"INTERNAL_SERVER":  0,
		"INVALID_ARGUMENT": 1,
	}
)

func (x ServerError) Enum() *ServerError {
	p := new(ServerError)
	*p = x
	return p
}

func (x ServerError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerError) Descriptor() protoreflect.EnumDescriptor {
	return file_error_proto_enumTypes[1].Descriptor()
}

func (ServerError) Type() protoreflect.EnumType {
	return &file_error_proto_enumTypes[1]
}

func (x ServerError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerError.Descriptor instead.
func (ServerError) EnumDescriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{1}
}

var File_error_proto protoreflect.FileDescriptor

var file_error_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x72,
	0x61, 0x62, 0x62, 0x69, 0x74, 0x2e, 0x6d, 0x65, 0x72, 0x72, 0x1a, 0x13, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x73, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a,
	0x86, 0x01, 0x0a, 0x0b, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x0a, 0x0a, 0x06, 0x50, 0x41, 0x52, 0x41, 0x4d, 0x53, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x49,
	0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x4f, 0x54,
	0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x02, 0x12, 0x16, 0x0a, 0x0c, 0x55, 0x4e, 0x41, 0x55,
	0x54, 0x48, 0x4f, 0x52, 0x49, 0x5a, 0x45, 0x44, 0x10, 0x03, 0x1a, 0x04, 0xa8, 0x45, 0x91, 0x03,
	0x12, 0x13, 0x0a, 0x09, 0x46, 0x4f, 0x52, 0x42, 0x49, 0x44, 0x44, 0x45, 0x4e, 0x10, 0x04, 0x1a,
	0x04, 0xa8, 0x45, 0x93, 0x03, 0x12, 0x1b, 0x0a, 0x11, 0x54, 0x4f, 0x4f, 0x5f, 0x4d, 0x41, 0x4e,
	0x59, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x53, 0x10, 0x05, 0x1a, 0x04, 0xa8, 0x45,
	0xad, 0x03, 0x1a, 0x04, 0xa0, 0x45, 0x90, 0x03, 0x2a, 0x3e, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x13, 0x0a, 0x0f, 0x49, 0x4e, 0x54, 0x45, 0x52,
	0x4e, 0x41, 0x4c, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10,
	0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x41, 0x52, 0x47, 0x55, 0x4d, 0x45, 0x4e, 0x54,
	0x10, 0x01, 0x1a, 0x04, 0xa0, 0x45, 0xf4, 0x03, 0x42, 0x3c, 0x0a, 0x0b, 0x72, 0x61, 0x62, 0x62,
	0x69, 0x74, 0x2e, 0x6d, 0x65, 0x72, 0x72, 0x50, 0x01, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x69, 0x64, 0x65, 0x2d, 0x66, 0x61, 0x6d, 0x69, 0x6c,
	0x79, 0x2f, 0x72, 0x61, 0x62, 0x62, 0x69, 0x74, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x65, 0x72,
	0x72, 0x3b, 0x6d, 0x65, 0x72, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_error_proto_rawDescOnce sync.Once
	file_error_proto_rawDescData = file_error_proto_rawDesc
)

func file_error_proto_rawDescGZIP() []byte {
	file_error_proto_rawDescOnce.Do(func() {
		file_error_proto_rawDescData = protoimpl.X.CompressGZIP(file_error_proto_rawDescData)
	})
	return file_error_proto_rawDescData
}

var file_error_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_error_proto_goTypes = []any{
	(ClientError)(0), // 0: rabbit.merr.ClientError
	(ServerError)(0), // 1: rabbit.merr.ServerError
}
var file_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_error_proto_init() }
func file_error_proto_init() {
	if File_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_error_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_error_proto_goTypes,
		DependencyIndexes: file_error_proto_depIdxs,
		EnumInfos:         file_error_proto_enumTypes,
	}.Build()
	File_error_proto = out.File
	file_error_proto_rawDesc = nil
	file_error_proto_goTypes = nil
	file_error_proto_depIdxs = nil
}
