// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package merr

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsParams(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ClientError_PARAMS.String() && e.Code == 400
}

func ErrorParams(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ClientError_PARAMS.String(), fmt.Sprintf(format, args...))
}

func IsInternal(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ClientError_INTERNAL.String() && e.Code == 400
}

func ErrorInternal(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ClientError_INTERNAL.String(), fmt.Sprintf(format, args...))
}

func IsNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ClientError_NOT_FOUND.String() && e.Code == 400
}

func ErrorNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ClientError_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsUnauthorized(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ClientError_UNAUTHORIZED.String() && e.Code == 401
}

func ErrorUnauthorized(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ClientError_UNAUTHORIZED.String(), fmt.Sprintf(format, args...))
}

func IsForbidden(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ClientError_FORBIDDEN.String() && e.Code == 403
}

func ErrorForbidden(format string, args ...interface{}) *errors.Error {
	return errors.New(403, ClientError_FORBIDDEN.String(), fmt.Sprintf(format, args...))
}

func IsTooManyRequests(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ClientError_TOO_MANY_REQUESTS.String() && e.Code == 429
}

func ErrorTooManyRequests(format string, args ...interface{}) *errors.Error {
	return errors.New(429, ClientError_TOO_MANY_REQUESTS.String(), fmt.Sprintf(format, args...))
}

func IsInternalServer(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ServerError_INTERNAL_SERVER.String() && e.Code == 500
}

func ErrorInternalServer(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ServerError_INTERNAL_SERVER.String(), fmt.Sprintf(format, args...))
}

func IsInvalidArgument(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ServerError_INVALID_ARGUMENT.String() && e.Code == 500
}

func ErrorInvalidArgument(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ServerError_INVALID_ARGUMENT.String(), fmt.Sprintf(format, args...))
}
