syntax = "proto3";

package internal.conf;

import "google/protobuf/duration.proto";
import "config/config.proto";
import "enum/enum.proto";

option go_package = "github.com/aide-family/rabbit/internal/conf;conf";

message Bootstrap {
	rabbit.enum.Environment environment = 1;
	string useRandomID = 2;
	Server server = 3;
	rabbit.config.JWT jwt = 4;
	rabbit.config.BasicAuthConfig swaggerBasicAuth = 5;
	rabbit.config.BasicAuthConfig metricsBasicAuth = 6;
	string enableSwagger = 7;
	string enableMetrics = 8;
	string enableClientConfig = 9;
	rabbit.config.ReportConfig report = 10;
	rabbit.config.OAuth2 oauth2 = 11;
	rabbit.config.DomainConfig namespaceConfig = 12;
	rabbit.config.DomainConfig loginConfig = 13;
}

message Server {
	message ServerConfig {
		string address = 1;
		string network = 2;
		google.protobuf.Duration timeout = 3;
		rabbit.config.Protocol protocol = 4;
	}
	
	string name = 1;
	map<string, string> metadata = 2;
	ServerConfig http = 3;
	ServerConfig grpc = 4;
}
