// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.3
// source: enum/enum.proto

package enum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Environment int32

const (
	Environment_UNKNOWN Environment = 0
	Environment_DEV     Environment = 1
	Environment_TEST    Environment = 2
	Environment_PREVIEW Environment = 3
	Environment_PROD    Environment = 4
)

// Enum value maps for Environment.
var (
	Environment_name = map[int32]string{
		0: "UNKNOWN",
		1: "DEV",
		2: "TEST",
		3: "PREVIEW",
		4: "PROD",
	}
	Environment_value = map[string]int32{
		"UNKNOWN": 0,
		"DEV":     1,
		"TEST":    2,
		"PREVIEW": 3,
		"PROD":    4,
	}
)

func (x Environment) Enum() *Environment {
	p := new(Environment)
	*p = x
	return p
}

func (x Environment) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Environment) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_enum_proto_enumTypes[0].Descriptor()
}

func (Environment) Type() protoreflect.EnumType {
	return &file_enum_enum_proto_enumTypes[0]
}

func (x Environment) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Environment.Descriptor instead.
func (Environment) EnumDescriptor() ([]byte, []int) {
	return file_enum_enum_proto_rawDescGZIP(), []int{0}
}

type GlobalStatus int32

const (
	GlobalStatus_GlobalStatus_UNKNOWN GlobalStatus = 0
	GlobalStatus_ENABLED              GlobalStatus = 1
	GlobalStatus_DISABLED             GlobalStatus = 2
)

// Enum value maps for GlobalStatus.
var (
	GlobalStatus_name = map[int32]string{
		0: "GlobalStatus_UNKNOWN",
		1: "ENABLED",
		2: "DISABLED",
	}
	GlobalStatus_value = map[string]int32{
		"GlobalStatus_UNKNOWN": 0,
		"ENABLED":              1,
		"DISABLED":             2,
	}
)

func (x GlobalStatus) Enum() *GlobalStatus {
	p := new(GlobalStatus)
	*p = x
	return p
}

func (x GlobalStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GlobalStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_enum_proto_enumTypes[1].Descriptor()
}

func (GlobalStatus) Type() protoreflect.EnumType {
	return &file_enum_enum_proto_enumTypes[1]
}

func (x GlobalStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GlobalStatus.Descriptor instead.
func (GlobalStatus) EnumDescriptor() ([]byte, []int) {
	return file_enum_enum_proto_rawDescGZIP(), []int{1}
}

type WebhookAPP int32

const (
	WebhookAPP_WebhookAPP_UNKNOWN WebhookAPP = 0
	WebhookAPP_OTHER              WebhookAPP = 2000
	WebhookAPP_DINGTALK           WebhookAPP = 2001
	WebhookAPP_WECHAT             WebhookAPP = 2002
	WebhookAPP_FEISHU             WebhookAPP = 2003
)

// Enum value maps for WebhookAPP.
var (
	WebhookAPP_name = map[int32]string{
		0:    "WebhookAPP_UNKNOWN",
		2000: "OTHER",
		2001: "DINGTALK",
		2002: "WECHAT",
		2003: "FEISHU",
	}
	WebhookAPP_value = map[string]int32{
		"WebhookAPP_UNKNOWN": 0,
		"OTHER":              2000,
		"DINGTALK":           2001,
		"WECHAT":             2002,
		"FEISHU":             2003,
	}
)

func (x WebhookAPP) Enum() *WebhookAPP {
	p := new(WebhookAPP)
	*p = x
	return p
}

func (x WebhookAPP) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebhookAPP) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_enum_proto_enumTypes[2].Descriptor()
}

func (WebhookAPP) Type() protoreflect.EnumType {
	return &file_enum_enum_proto_enumTypes[2]
}

func (x WebhookAPP) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WebhookAPP.Descriptor instead.
func (WebhookAPP) EnumDescriptor() ([]byte, []int) {
	return file_enum_enum_proto_rawDescGZIP(), []int{2}
}

type HTTPMethod int32

const (
	HTTPMethod_HTTPMethod_UNKNOWN HTTPMethod = 0
	HTTPMethod_GET                HTTPMethod = 1
	HTTPMethod_POST               HTTPMethod = 2
	HTTPMethod_PUT                HTTPMethod = 3
	HTTPMethod_DELETE             HTTPMethod = 4
	HTTPMethod_PATCH              HTTPMethod = 5
)

// Enum value maps for HTTPMethod.
var (
	HTTPMethod_name = map[int32]string{
		0: "HTTPMethod_UNKNOWN",
		1: "GET",
		2: "POST",
		3: "PUT",
		4: "DELETE",
		5: "PATCH",
	}
	HTTPMethod_value = map[string]int32{
		"HTTPMethod_UNKNOWN": 0,
		"GET":                1,
		"POST":               2,
		"PUT":                3,
		"DELETE":             4,
		"PATCH":              5,
	}
)

func (x HTTPMethod) Enum() *HTTPMethod {
	p := new(HTTPMethod)
	*p = x
	return p
}

func (x HTTPMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HTTPMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_enum_proto_enumTypes[3].Descriptor()
}

func (HTTPMethod) Type() protoreflect.EnumType {
	return &file_enum_enum_proto_enumTypes[3]
}

func (x HTTPMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HTTPMethod.Descriptor instead.
func (HTTPMethod) EnumDescriptor() ([]byte, []int) {
	return file_enum_enum_proto_rawDescGZIP(), []int{3}
}

type MessageStatus int32

const (
	MessageStatus_MessageStatus_UNKNOWN MessageStatus = 0
	MessageStatus_PENDING               MessageStatus = 1
	MessageStatus_SENDING               MessageStatus = 2
	MessageStatus_SENT                  MessageStatus = 3
	MessageStatus_FAILED                MessageStatus = 4
	MessageStatus_CANCELLED             MessageStatus = 5
)

// Enum value maps for MessageStatus.
var (
	MessageStatus_name = map[int32]string{
		0: "MessageStatus_UNKNOWN",
		1: "PENDING",
		2: "SENDING",
		3: "SENT",
		4: "FAILED",
		5: "CANCELLED",
	}
	MessageStatus_value = map[string]int32{
		"MessageStatus_UNKNOWN": 0,
		"PENDING":               1,
		"SENDING":               2,
		"SENT":                  3,
		"FAILED":                4,
		"CANCELLED":             5,
	}
)

func (x MessageStatus) Enum() *MessageStatus {
	p := new(MessageStatus)
	*p = x
	return p
}

func (x MessageStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_enum_proto_enumTypes[4].Descriptor()
}

func (MessageStatus) Type() protoreflect.EnumType {
	return &file_enum_enum_proto_enumTypes[4]
}

func (x MessageStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageStatus.Descriptor instead.
func (MessageStatus) EnumDescriptor() ([]byte, []int) {
	return file_enum_enum_proto_rawDescGZIP(), []int{4}
}

type MessageType int32

const (
	MessageType_MessageType_UNKNOWN MessageType = 0
	MessageType_EMAIL               MessageType = 1
	MessageType_SMS_ALICLOUD        MessageType = 1000
	MessageType_WEBHOOK_OTHER       MessageType = 2000
	MessageType_WEBHOOK_DINGTALK    MessageType = 2001
	MessageType_WEBHOOK_WECHAT      MessageType = 2002
	MessageType_WEBHOOK_FEISHU      MessageType = 2003
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:    "MessageType_UNKNOWN",
		1:    "EMAIL",
		1000: "SMS_ALICLOUD",
		2000: "WEBHOOK_OTHER",
		2001: "WEBHOOK_DINGTALK",
		2002: "WEBHOOK_WECHAT",
		2003: "WEBHOOK_FEISHU",
	}
	MessageType_value = map[string]int32{
		"MessageType_UNKNOWN": 0,
		"EMAIL":               1,
		"SMS_ALICLOUD":        1000,
		"WEBHOOK_OTHER":       2000,
		"WEBHOOK_DINGTALK":    2001,
		"WEBHOOK_WECHAT":      2002,
		"WEBHOOK_FEISHU":      2003,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_enum_proto_enumTypes[5].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_enum_enum_proto_enumTypes[5]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_enum_enum_proto_rawDescGZIP(), []int{5}
}

var File_enum_enum_proto protoreflect.FileDescriptor

var file_enum_enum_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x65, 0x6e, 0x75, 0x6d, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0b, 0x72, 0x61, 0x62, 0x62, 0x69, 0x74, 0x2e, 0x65, 0x6e, 0x75, 0x6d, 0x2a, 0x44,
	0x0a, 0x0b, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x0b, 0x0a,
	0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x44, 0x45,
	0x56, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x45, 0x53, 0x54, 0x10, 0x02, 0x12, 0x0b, 0x0a,
	0x07, 0x50, 0x52, 0x45, 0x56, 0x49, 0x45, 0x57, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x52,
	0x4f, 0x44, 0x10, 0x04, 0x2a, 0x43, 0x0a, 0x0c, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x14, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0b,
	0x0a, 0x07, 0x45, 0x4e, 0x41, 0x42, 0x4c, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x44,
	0x49, 0x53, 0x41, 0x42, 0x4c, 0x45, 0x44, 0x10, 0x02, 0x2a, 0x59, 0x0a, 0x0a, 0x57, 0x65, 0x62,
	0x68, 0x6f, 0x6f, 0x6b, 0x41, 0x50, 0x50, 0x12, 0x16, 0x0a, 0x12, 0x57, 0x65, 0x62, 0x68, 0x6f,
	0x6f, 0x6b, 0x41, 0x50, 0x50, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12,
	0x0a, 0x0a, 0x05, 0x4f, 0x54, 0x48, 0x45, 0x52, 0x10, 0xd0, 0x0f, 0x12, 0x0d, 0x0a, 0x08, 0x44,
	0x49, 0x4e, 0x47, 0x54, 0x41, 0x4c, 0x4b, 0x10, 0xd1, 0x0f, 0x12, 0x0b, 0x0a, 0x06, 0x57, 0x45,
	0x43, 0x48, 0x41, 0x54, 0x10, 0xd2, 0x0f, 0x12, 0x0b, 0x0a, 0x06, 0x46, 0x45, 0x49, 0x53, 0x48,
	0x55, 0x10, 0xd3, 0x0f, 0x2a, 0x57, 0x0a, 0x0a, 0x48, 0x54, 0x54, 0x50, 0x4d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x12, 0x16, 0x0a, 0x12, 0x48, 0x54, 0x54, 0x50, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x47, 0x45,
	0x54, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x4f, 0x53, 0x54, 0x10, 0x02, 0x12, 0x07, 0x0a,
	0x03, 0x50, 0x55, 0x54, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45,
	0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x41, 0x54, 0x43, 0x48, 0x10, 0x05, 0x2a, 0x69, 0x0a,
	0x0d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x19,
	0x0a, 0x15, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f,
	0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x45, 0x4e,
	0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x45, 0x4e, 0x44, 0x49, 0x4e,
	0x47, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x45, 0x4e, 0x54, 0x10, 0x03, 0x12, 0x0a, 0x0a,
	0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x41, 0x4e,
	0x43, 0x45, 0x4c, 0x4c, 0x45, 0x44, 0x10, 0x05, 0x2a, 0x99, 0x01, 0x0a, 0x0b, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x13, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10,
	0x00, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x4d, 0x41, 0x49, 0x4c, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0c,
	0x53, 0x4d, 0x53, 0x5f, 0x41, 0x4c, 0x49, 0x43, 0x4c, 0x4f, 0x55, 0x44, 0x10, 0xe8, 0x07, 0x12,
	0x12, 0x0a, 0x0d, 0x57, 0x45, 0x42, 0x48, 0x4f, 0x4f, 0x4b, 0x5f, 0x4f, 0x54, 0x48, 0x45, 0x52,
	0x10, 0xd0, 0x0f, 0x12, 0x15, 0x0a, 0x10, 0x57, 0x45, 0x42, 0x48, 0x4f, 0x4f, 0x4b, 0x5f, 0x44,
	0x49, 0x4e, 0x47, 0x54, 0x41, 0x4c, 0x4b, 0x10, 0xd1, 0x0f, 0x12, 0x13, 0x0a, 0x0e, 0x57, 0x45,
	0x42, 0x48, 0x4f, 0x4f, 0x4b, 0x5f, 0x57, 0x45, 0x43, 0x48, 0x41, 0x54, 0x10, 0xd2, 0x0f, 0x12,
	0x13, 0x0a, 0x0e, 0x57, 0x45, 0x42, 0x48, 0x4f, 0x4f, 0x4b, 0x5f, 0x46, 0x45, 0x49, 0x53, 0x48,
	0x55, 0x10, 0xd3, 0x0f, 0x42, 0x3c, 0x0a, 0x0b, 0x72, 0x61, 0x62, 0x62, 0x69, 0x74, 0x2e, 0x65,
	0x6e, 0x75, 0x6d, 0x50, 0x01, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x61, 0x69, 0x64, 0x65, 0x2d, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x2f, 0x72, 0x61,
	0x62, 0x62, 0x69, 0x74, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x3b, 0x65, 0x6e,
	0x75, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_enum_enum_proto_rawDescOnce sync.Once
	file_enum_enum_proto_rawDescData = file_enum_enum_proto_rawDesc
)

func file_enum_enum_proto_rawDescGZIP() []byte {
	file_enum_enum_proto_rawDescOnce.Do(func() {
		file_enum_enum_proto_rawDescData = protoimpl.X.CompressGZIP(file_enum_enum_proto_rawDescData)
	})
	return file_enum_enum_proto_rawDescData
}

var file_enum_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_enum_enum_proto_goTypes = []any{
	(Environment)(0),   // 0: rabbit.enum.Environment
	(GlobalStatus)(0),  // 1: rabbit.enum.GlobalStatus
	(WebhookAPP)(0),    // 2: rabbit.enum.WebhookAPP
	(HTTPMethod)(0),    // 3: rabbit.enum.HTTPMethod
	(MessageStatus)(0), // 4: rabbit.enum.MessageStatus
	(MessageType)(0),   // 5: rabbit.enum.MessageType
}
var file_enum_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enum_enum_proto_init() }
func file_enum_enum_proto_init() {
	if File_enum_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_enum_enum_proto_rawDesc,
			NumEnums:      6,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enum_enum_proto_goTypes,
		DependencyIndexes: file_enum_enum_proto_depIdxs,
		EnumInfos:         file_enum_enum_proto_enumTypes,
	}.Build()
	File_enum_enum_proto = out.File
	file_enum_enum_proto_rawDesc = nil
	file_enum_enum_proto_goTypes = nil
	file_enum_enum_proto_depIdxs = nil
}
